# Generated by Django 4.2.3 on 2023-08-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marvel',
            fields=[
                ('movie_base', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Relese_date', models.DateField()),
                ('Ott', models.URLField()),
                ('movie_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marvel')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movies')),
            ],
        ),
    ]
